routes/item.py
from flask import Blueprint, request, render_template

from routes.common import get_data_from_file, get_pages_indexes, get_results


item_bp = Blueprint('item', __name__)

def find_item_detail(items, item_id):
    for item in items:
        if item['id'] == item_id:
            item_info = item
            return item_info
    return None

@item_bp.route('/items/')
def items():
    page = request.args.get('page', default=1, type=int)

    items = get_data_from_file('src/item.csv')
    total_pages, start_index, end_index =  get_pages_indexes(len(items), page)

    return render_template("common/list.html", model="item", data=items[start_index:end_index],
                           total_pages=total_pages, page=page)

@item_bp.route('/item_detail/')
def item_detail():
    item_id = request.args.get('id', default="", type=str)

    items = get_data_from_file('src/item.csv')
    item_info = find_item_detail(items, item_id)

    return render_template("common/detail.html", model="item", detail_info=item_info)

routes/order.py
from flask import Blueprint, request, render_template

from routes.common import get_data_from_file, get_pages_indexes, get_results


order_bp = Blueprint('order', __name__)

def find_order_detail(orders, order_id):
    for order in orders:
        if order['id'] == order_id:
            order_info = order
            return order_info
    return None

@order_bp.route('/orders/')
def orders():
    page = request.args.get('page', default=1, type=int)

    orders = get_data_from_file('src/order.csv')
    total_pages, start_index, end_index =  get_pages_indexes(len(orders), page)

    return render_template("common/list.html", model="order", data=orders[start_index:end_index],
                           total_pages=total_pages, page=page)

@order_bp.route('/order_detail/')
def order_detail():
    order_id = request.args.get('id', default="", type=str)
    
    orders = get_data_from_file('src/order.csv')
    order_info = find_order_detail(orders, order_id)

    return render_template("common/detail.html", model="order", detail_info=order_info)

routes/orderitem.py
from flask import Blueprint, request, render_template

from routes.common import get_data_from_file, get_pages_indexes, get_results


orderitem_bp = Blueprint('orderitem', __name__)

def find_orderitem_detail(orderitem, orderitem_id):
    for oi in orderitem:
        if oi['id'] == orderitem_id:
            order_info = oi
            return order_info
    return None

@orderitem_bp.route('/orderitem/')
def orderitem():
    page = request.args.get('page', default=1, type=int)

    orderitem = get_data_from_file('src/orderlist.csv')
    total_pages, start_index, end_index =  get_pages_indexes(len(orderitem), page)

    return render_template("common/list.html", model="orderitem", data=orderitem[start_index:end_index],
                           total_pages=total_pages, page=page)

@orderitem_bp.route('/orderitem_detail/')
def orderitem_detail():
    orderitem_id = request.args.get('id', default="", type=str)
    
    orderitem = get_data_from_file('src/orderlist.csv')
    orderitem_info = find_orderitem_detail(orderitem, orderitem_id)

    return render_template("common/detail.html", model="orderitem", detail_info=orderitem_info)

routes/store.py
from flask import Blueprint, request, render_template

from routes.common import get_data_from_file, get_pages_indexes, get_results


store_bp = Blueprint('store', __name__)
            
def find_store_detail(stores, store_id) :
    for store in stores:
        if store['id'] == store_id:
            store_info = store
            return store_info
    return None

@store_bp.route("/stores/")
def stores():
    page = request.args.get('page', default=1, type=int)

    stores = get_data_from_file('src/store.csv')
    total_pages, start_index, end_index =  get_pages_indexes(len(stores), page)

    return render_template("common/list.html", model="store", data=stores[start_index:end_index],
                           total_pages=total_pages, page=page)

@store_bp.route("/store_detail/")
def store_detail():
    store_id = request.args.get('id', default="", type=str)

    stores = get_data_from_file('src/store.csv')
    store_info = find_store_detail(stores, store_id)

    return render_template("common/detail.html", model="store", detail_info=store_info)

routes/user.py
from flask import Blueprint, request, render_template

from routes.common import get_data_from_file, get_pages_indexes, get_results


user_bp = Blueprint('user', __name__)

# 프론트에서 처리
def filter_data(data, search_name="", search_gender="", search_age=0):
    filtered_data = []
    highlighted = []
    if bool(search_name) or bool(search_gender) or bool(search_age) : # 검색어가 있다면 데이터 필터링
        for d in data:
            if (is_name_match(search_name, d['name']) and
                is_gender_match(search_gender, d['gender']) and
                is_age_match(search_age, int(d['age']))) :
                filtered_data.append(d)
                match = [0 for _ in range(len(d['name']))] # match되는 부분을 저장할 list
                if (search_name) :
                    for i in range(len(d['name'])-len(search_name)+1):
                        if d['name'][i:i+len(search_name)] == search_name:
                            # match하면 1, 아니면 0으로 남아있음
                            match[i:i+len(search_name)] = [1 for _ in range(i, i+len(search_name))]
                highlighted.append(match)
    else : # 없으면 원래 데이터
        filtered_data = data
    print(highlighted)
    return filtered_data, highlighted

def find_user_detail(users, user_id) :
    for user in users:
        if user['id'] == user_id :
            user_info = user
            return user_info
    return None

def is_name_match(search_name, data_name):
    if (search_name in data_name) :
        return True
    return False

def is_gender_match(search_gender, data_gender):
    if not search_gender:
        return True
    elif (search_gender.lower() == data_gender.lower()):
        return True
    return False

def is_age_match(search_age, data_age):
    if search_age == 0:
        return True
    elif data_age // 10 * 10 == search_age :
        return True
    else :
        return False
    
# 폴더 안에 user util user routes

@user_bp.route("/users/")
def users():
    page = request.args.get('page', default=1, type=int)
    search_name = request.args.get('name', default="", type=str)
    search_gender = request.args.get('gender', default="", type=str)
    search_age = request.args.get('age', default=0, type=int)

    data = get_data_from_file('src/user.csv') # 데이터 불러오기
    final_data, highlighted = filter_data(data, search_name, search_gender, search_age)
    total_pages, start_index, end_index =  get_pages_indexes(len(final_data), page)

    return render_template("users.html", users=final_data[start_index:end_index], highlighted=highlighted[start_index:end_index],
                           total_pages=total_pages, page=page, 
                           search_name=search_name, search_gender= search_gender, search_age = search_age)

@user_bp.route("/user_detail/")
def user_detail():
    user_id = request.args.get('id', default="", type=str)

    users = get_data_from_file('src/user.csv')
    user_info = find_user_detail(users, user_id)

    print("user",user_info)
    return render_template("common/detail.html", model="user", detail_info=user_info)

views/item_view.py
from flask import Blueprint, render_template, request

from sqlalchemy import and_
from sqlalchemy import func
from database.model import db, User, Store, Item, Order, OrderItem


item_bp = Blueprint('item', __name__)

def get_length(model):
    count = db.session.query(func.count(model.Id)) \
        .first()
    return int(count[0])

def get_pages_indexes(data_length, page):
    per_page = 20
    total_pages = (data_length - 1) // per_page + 1
    start_index = (page - 1) * per_page
    return total_pages, per_page, start_index

@item_bp.route('/items/')
def items():
    page = request.args.get('page', default=1, type=int)

    length = get_length(Item)
    total_pages, per_page, start_index = get_pages_indexes(length, page)

    items = Item.query \
        .offset(start_index) \
        .limit(per_page) \
        .all()
    
    header = ['Id', 'Name', 'Type', 'UnitPrice']
    return render_template("items.html", items=items,
                           total_pages=total_pages, page=page, header=header)

@item_bp.route('/item_detail/')
def item_detail():
    item_id = request.args.get('id', default=1, type=str)

    item_info = Item.query.filter_by(Id=item_id).first()

    return render_template("item_detail.html", model="item", detail_info=item_info)

views/order_view.py
from flask import Blueprint, render_template, request

from sqlalchemy import and_
from sqlalchemy import func
from database.model import db, User, Store, Item, Order, OrderItem


order_bp = Blueprint('order', __name__)

def get_pages_indexes(data_length, page):
    per_page = 20
    total_pages = (data_length - 1) // per_page + 1
    start_index = (page - 1) * per_page
    return total_pages, per_page, start_index

def get_length(model):
    count = db.session.query(func.count(model.Id)) \
        .first()
    return int(count[0])

@order_bp.route('/orders/')
def orders():
    page = request.args.get('page', default=1, type=int)

    length = get_length(Order)
    total_pages, per_page, start_index = get_pages_indexes(length, page)
    
    orders = Order.query \
        .offset(start_index) \
        .limit(per_page) \
        .all()

    header = ['Id', 'OrderAt', 'StoreId', 'UserId']
    return render_template("orders.html", data=orders,
                           total_pages=total_pages, page=page, header=header)

@order_bp.route('/order_detail/')
def order_detail():
    order_id = request.args.get('id', default="", type=str)
    
    order_info = Order.query.filter_by(Id=order_id).first()

    return render_template("order_detail.html", model="order", detail_info=order_info)

views/orderitem_view.py
from flask import Blueprint, render_template, request

from sqlalchemy import and_
from sqlalchemy import func
from database.model import db, User, Store, Item, Order, OrderItem


orderitem_bp = Blueprint('orderitem', __name__)

def get_pages_indexes(data_length, page):
    per_page = 20
    total_pages = (data_length - 1) // per_page + 1
    start_index = (page - 1) * per_page
    return total_pages, per_page, start_index

def get_length(model):
    count = db.session.query(func.count(model.Id)) \
        .first()
    return int(count[0])

@orderitem_bp.route('/orderitems/')
def orderitems():
    page = request.args.get('page', default=1, type=int)

    length = get_length(OrderItem)
    total_pages, per_page, start_index = get_pages_indexes(length, page)

    orderitems = OrderItem.query \
        .offset(start_index) \
        .limit(per_page) \
        .all()
    
    header = ['Id', 'OrderId', 'ItemId']
    return render_template("orderitems.html", data=orderitems,
                           total_pages=total_pages, page=page, header=header)

@orderitem_bp.route('/orderitem_detail/')
def orderitem_detail():
    orderitem_id = request.args.get('id', default="", type=str)
    
    orderitem_info = OrderItem.query.filter_by(Id=orderitem_id).first()

    return render_template("orderitem_detail.html", model="order", detail_info=orderitem_info)

views/store_view.py
from flask import Blueprint, render_template, request

from sqlalchemy import and_
from sqlalchemy import func
from database.model import db, User, Store, Item, Order, OrderItem


store_bp = Blueprint('store', __name__)

def get_length(model):
    count = db.session.query(func.count(model.Id)) \
        .first()
    return int(count[0])

def get_pages_indexes(data_length, page):
    per_page = 20
    total_pages = (data_length - 1) // per_page + 1
    start_index = (page - 1) * per_page
    return total_pages, per_page, start_index

@store_bp.route('/stores/')
def stores():
    page = request.args.get('page', default=1, type=int)

    length = get_length(Store)
    total_pages, per_page, start_index = get_pages_indexes(length, page)

    stores = Store.query \
        .offset(start_index) \
        .limit(per_page) \
        .all()
    
    header = ['Id', 'Name', 'Type', 'Address']
    return render_template("stores.html", stores=stores,
                           total_pages=total_pages, page=page, header=header)

@store_bp.route('/store_detail/')
def store_detail():
    store_id = request.args.get('id', default="", type=str)

    store_info = Store.query.filter_by(Id=store_id).first()

    # sales_per_month_info
    sales_per_month_info = db.session.query(Store.Name.label("storename"), func.substr(Order.OrderAt, 0, 8).label("month"), func.sum(Item.UnitPrice).label("total_revenue"), func.count(Item.Id).label("item_count")) \
        .join(Order, Order.StoreId == Store.Id) \
        .join(OrderItem, Order.Id == OrderItem.OrderId) \
        .join(Item, Item.Id == OrderItem.ItemId) \
        .filter(Store.Id == store_id) \
        .group_by(func.substr(Order.OrderAt, 0, 8)) \
        .all()

    return render_template("store_detail.html", model="store", detail_info=store_info,
                           sales_per_month_info=sales_per_month_info)

views/user_view.py
from flask import Blueprint, render_template, request
from sqlalchemy import and_
from sqlalchemy import func
import datetime
import uuid

from database.model import db, User, Store, Item, Order, OrderItem


user_bp = Blueprint('user', __name__)

def get_pages_indexes(data_length, page):
    per_page = 20
    total_pages = (data_length - 1) // per_page + 1
    start_index = (page - 1) * per_page
    return total_pages, per_page, start_index

def get_length_users(search_name, search_gender, search_age) :
    users_count = db.session.query(func.count(User.Id)) \
        .filter(User.Name.like('%'+search_name+'%')) \
        .filter(User.Gender.like(search_gender+'%'))\
        .filter(and_(search_age < User.Age, User.Age < search_age + 9)) \
        .first()
    return int(users_count[0])

def get_age(birthdate) :
    dateToday = datetime.datetime.now()
    if birthdate :
        age = dateToday.year - int(birthdate[:4]) + 1
    return age

def generate_id():
    return str(uuid.uuid4())

@user_bp.route('/users/')
def users():
    page = request.args.get('page', default=1, type=int)
    search_name = request.args.get('name', default='', type=str)
    search_gender = request.args.get('gender', default='', type=str)
    search_age = request.args.get('age', default=0, type=int)

    length = get_length_users(search_name, search_gender, search_age)
    total_pages, per_page, start_index = get_pages_indexes(length, page)

    users = User.query \
        .filter(User.Name.like('%'+search_name+'%')) \
        .filter(User.Gender.like(search_gender+'%')) \
        .filter(and_(search_age < User.Age, User.Age < search_age + 9)) \
        .offset(start_index) \
        .limit(per_page) \
        .all()

    header = ['Id', 'Name', 'Gender', 'Age', 'Birthdate', 'Address']
    return render_template("users.html", users=users,
                           total_pages=total_pages, page=page, header=header,
                           search_name=search_name, search_gender=search_gender, search_age=search_age)

@user_bp.route('/user_detail/')
def user_detail():
    user_id = request.args.get('id', default="", type=str)

    user_info = User.query.filter_by(Id=user_id).first()

    # user_purchased_info
    user_purchased_info = db.session.query(User.Name.label("username"), Order.Id.label("orderid"), Order.OrderAt.label("orderat"), Store.Name.label("storename")) \
        .join(Order, Order.UserId == User.Id) \
        .join(Store, Store.Id == Order.StoreId) \
        .filter(User.Id == user_id) \
        .all()

    # user_top_store_info
    user_top_store_info = db.session.query(User.Name.label("username"), Store.Name.label("storename"), func.count(Order.Id).label("count_visited")) \
        .join(Order, Order.UserId == User.Id) \
        .join(Store, Store.Id == Order.StoreId) \
        .group_by(Store.Id) \
        .order_by(func.count(Order.Id).desc()) \
        .filter(User.Id == user_id) \
        .limit(5) \
        .all()

    # user_top_item_info
    user_top_item_info = db.session.query(User.Name.label("username"), Item.Name.label("itemname"), func.count(Order.Id).label("count_ordered")) \
        .join(Order, User.Id == Order.UserId) \
        .join(OrderItem, Order.Id == OrderItem.OrderId) \
        .join(Item, Item.Id == OrderItem.ItemId) \
        .group_by(Item.Id) \
        .order_by(func.count(Order.Id).desc()) \
        .filter(User.Id == user_id) \
        .limit(5) \
        .all()

    return render_template("user_detail.html", model="user", detail_info=user_info,
                           purchased_info=user_purchased_info, top_store=user_top_store_info, top_item=user_top_item_info)

@user_bp.route("/user/register", methods=['GET', 'POST'])
def user_register():
    if request.method == 'POST' :
        get = request.form
        new_user = User(Id=generate_id(), Name=get['name'], Gender=get['gender'], Age=get_age(get['birthdate']), Birthdate=get['birthdate'], Address=get['address'])
        db.session.add(new_user)
        db.session.commit()
        return render_template('register_complete.html', new_data=new_user)
    return render_template('user_register.html')

templates/home.html
{% extends 'common/base.html' %} 

{% block title%}
CRM - HOME
{% endblock %}

{% block content %}

<div class="sub-menu">
  <button>
    <a href="/kiosk">kiosk</a>
  </button>
  <a href="/user/register" class="filter">사용자 등록하기</a>
  <a href="/store/register" class="filter">상점 등록하기</a>
  <a href="/item/register" class="filter">상품 등록하기</a>
</div>

{% endblock %}

templates/item_detail.html
{% extends 'common/base.html' %}

{% block title%}
CRM - {{model}}
{% endblock %}

{% block content %}

{% if model == "user" %}
<h2>User '{{detail_info['Name']}}'님</h2>
{% elif model == "store" %}
<h2>Store '{{detail_info['Name']}}'</h2>
{% elif model == "order" %}
<h2>Order Id '{{detail_info['Id']}}'</h2>
{% elif model == "orderitem" %}
<h2>Order Item '{{detail_info['Id']}}'</h2>
{% elif model == "item" %}
<h2>Item '{{detail_info['Name']}}'</h2>
{% endif %}

<table class="info-table">
  <tr class="info-row">
    <th class="info-type">
      Id
    </th>
    <th class="info-type">
      Name
    </th>
    <th class="info-type">
      Type
    </th>
    <th class="info-type">
      UnitPrice
    </th>
  </tr>
  <tr class="info-row">
    <td class="info-single-item">
      {{ detail_info.Id }}
    </td>
    <td class="info-single-item">
      {{ detail_info.Name }}
    </td>
    <td class="info-single-item">
      {{ detail_info.Type }}
    </td>
    <td class="info-single-item">
      {{ detail_info.UnitPrice }}
    </td>
  </tr>
</table>

<button onclick="window.history.back()">뒤로 돌아가기</button>

{% endblock %}

templates/items.html
{% extends 'common/base.html' %} 

{% block title%}
CRM - ITEMS
{% endblock %}

{% block content %}

<!-- 
==================
      table
==================
-->

{% if items %}
<table class="info-table">
  <thead>
    <tr class="info-row">
      {% for key in header %}
      <th class="info-type">
        {{ key }}
      </th>
      {% endfor %}
    </tr>
  </thead>
  <tbody>
    {% for item in items %}
    <tr class="info-row background">
      <td class="info-single-item">
        <a href="{{ url_for('item.item_detail', id=item.Id) }}">
          {{ item.Id }}
        </a>
      </td>
      <td class="info-single-item">
        {{ item.Name }}
      </td>
      <td class="info-single-item">
        {{ item.Type }}
      </td>
      <td class="info-single-item">
        {{ item.UnitPrice }}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %}

<!-- 
==================
    pagination
==================
-->

{% set keywords = '' %}
{% include 'common/pagination.html'%}
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>USERS - CRM</title>
  <link href='{{url_for("static", filename="style.css")}}' rel="stylesheet">
  <style></style>
</head>

<body>
  <div class="main-container">
    <!-- 
    ==================
          menu bar
    ==================
    -->
    {% include "menu.html" %}

    {% block content %}
    <!-- 
    ==================
        main content
    ==================
    -->
    {% endblock %}

  </div>
</body>

</html>

templates/list.html
{% extends 'layout.html' %} {% block content %}

<table class="info-table">
  <tr class="info-row">
    {% for key in data[0].keys() %}
    <th class="info-type">
      {{ key }}
    </th>
    {% endfor %}
  </tr>
  {% for d in data %}
  <tr class="info-row background">
    {% for key in data[0].keys() %}
    <td class="info-single-item">
      {% if key == 'id' %}
      <a class="id-link" href="/{{model}}_detail/?id={{d[key]}}">{{ d[key] }}</a>
      {% else %}
      {{ d[key] }}
      {% endif %}
    </td>
    {% endfor %}
  </tr>
  {% endfor %}
</table>

{% set keywords = '' %}
{% include 'pagination.html'%}

{% endblock %}

templates/order_detail.html
{% extends 'common/base.html' %}

{% block title%}
CRM - {{model}}
{% endblock %}

{% block content %}

<h2>Order Id '{{detail_info['Id']}}'</h2>

<table class="info-table">
  <tr class="info-row">
    <th class="info-type">
      Id
    </th>
    <th class="info-type">
      OrderAt
    </th>
    <th class="info-type">
      StoreId
    </th>
    <th class="info-type">
      UserId
    </th>
  </tr>
  <tr class="info-row">
    <td class="info-single-item">
      {{ detail_info.Id }}
    </td>
    <td class="info-single-item">
      {{ detail_info.OrderAt }}
    </td>
    <td class="info-single-item">
      <a href="{{ url_for('store.store_detail', id=detail_info.StoreId) }}">
        {{ detail_info.StoreId }}
      </a>
    </td>
    <td class="info-single-item">
      <a href="{{ url_for('user.user_detail', id=detail_info.UserId) }}">
        {{ detail_info.UserId }}
      </a>
    </td>
  </tr>
</table>

<button onclick="window.history.back()">뒤로 돌아가기</button>

{% endblock %}

templates/orderitem_detail.html
{% extends 'common/base.html' %}

{% block title%}
CRM - {{model}}
{% endblock %}

{% block content %}

<h2>Order Item '{{detail_info['Id']}}'</h2>

<table class="info-table">
  <tr class="info-row">
    <th class="info-type">
      Id
    </th>
    <th class="info-type">
      OrderId
    </th>
    <th class="info-type">
      ItemId
    </th>
  </tr>
  <tr class="info-row">
    <td class="info-single-item">
      {{ detail_info.Id }}
    </td>
    <td class="info-single-item">
      <a href="{{ url_for('order.order_detail', id=detail_info.OrderId) }}">
        {{ detail_info.OrderId }}
      </a>
    </td>
    <td class="info-single-item">
      <a href="{{ url_for('item.item_detail', id=detail_info.ItemId) }}">
        {{ detail_info.ItemId }}
      </a>
    </td>
  </tr>
</table>

<button onclick="window.history.back()">뒤로 돌아가기</button>

{% endblock %}

templates/orderitems.html
{% extends 'common/base.html' %} 

{% block title%}
CRM - ORDERITEMS
{% endblock %}

{% block content %}

<table class="info-table">
  <tr class="info-row">
    {% for key in header %}
    <th class="info-type">
      {{ key }}
    </th>
    {% endfor %}
  </tr>
  {% for d in data %}
  <tr class="info-row background">
    <td class="info-single-item">
      <a href="{{ url_for('orderitem.orderitem_detail', id=d.Id) }}">
        {{ d.Id }}
      </a>
    </td>
    <td class="info-single-item">
      <a href="{{ url_for('order.order_detail', id=d.OrderId) }}">
        {{ d.OrderId }}
      </a>
    </td>
    <td class="info-single-item">
      <a href="{{ url_for('item.item_detail', id=d.ItemId) }}">
        {{ d.ItemId }}
      </a>
    </td>
  </tr>
  {% endfor %}
</table>

{% set keywords = '' %}
{% include 'common/pagination.html'%}

{% endblock %}

templates/orders.html
{% extends 'common/base.html' %}

{% block title %}
CRM - Order
{% endblock %}

{% block content %}

<table class="info-table">
  <tr class="info-row">
    {% for key in header %}
    <th class="info-type">
      {{ key }}
    </th>
    {% endfor %}
  </tr>
  {% for d in data %}
  <tr class="info-row background">
    <td class="info-single-item">
      <a href="{{ url_for('order.order_detail', id=d.Id) }}">
        {{ d.Id }}
      </a>
    </td>
    <td class="info-single-item">
      {{ d.OrderAt }}
    </td>
    <td class="info-single-item">
      <a href="{{ url_for('store.store_detail', id=d.StoreId) }}">
        {{ d.StoreId }}
      </a>
    </td>
    <td class="info-single-item">
      <a href="{{ url_for('user.user_detail', id=d.UserId) }}">
        {{ d.UserId }}
      </a>
    </td>
  </tr>
  {% endfor %}
</table>

{% set keywords = '' %}
{% include 'common/pagination.html' %}

{% endblock %}

templates/register_complete.html
{% extends 'common/base.html' %}

{% block title%}
Complete Register
{% endblock %}

{% block content %}
<h2>등록된 사용자 정보</h2>
{{ new_data }}
{{ new_data.Id }}
{{ new_data.Name }}
{{ new_data.Gender }}
{{ new_data.Birthdate }}
{{ new_data.Age }}
{{ new_data.Address }}



<a href="/">홈으로 이동하기</a>
{% endblock %}

templates/stores.html
{% extends 'common/base.html' %} 

{% block title%}
CRM - STORES
{% endblock %}

{% block content %}

<!-- 
==================
      table
==================
-->

{% if stores %}
<table class="info-table">
  <thead>
    <tr class="info-row">
      {% for key in header %}
      <th class="info-type">
        {{ key }}
      </th>
      {% endfor %}
    </tr>
  </thead>
  <tbody>
    {% for store in stores %}
    <tr class="info-row background">
      <td class="info-single-item">
        <a href="{{ url_for('store.store_detail', id=store.Id) }}">
          {{ store.Id }}
        </a>
      </td>
      <td class="info-single-item">
        {{ store.Name }}
      </td>
      <td class="info-single-item">
        {{ store.Type }}
      </td>
      <td class="info-single-item">
        {{ store.Address }}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %}

<!-- 
==================
    pagination
==================
-->

{% set keywords = '' %}
{% include 'common/pagination.html'%}
{% endblock %}

templates/users.html
{% extends 'common/base.html' %} 

{% block title%}
CRM - USERS
{% endblock %}

{% block content %}

<!-- 
==================
    search bar
==================
-->

<div class="search">
  <form class="search-form" action="/users/" method="GET">
    <div>
      <label for="name">Name :</label>
      <input name="name" class="input-form" type="text" value="{{search_name}}" size="5" />
    </div>
    <div>
      <label for="gender">Gender :</label>
      <select name="gender" class="input-form">
        <option value="" ></option>
        <option value="Female" {% if search_gender == "Female"%} selected {% endif %}>Female</option>
        <option value="Male" {% if search_gender == "Male" %} selected {% endif %}>Male</option>
      </select>
    </div>
    <button type="submit">검색</button>
  </form>
</div>
<div class="sub-menu">
  <a class="filter" href="{{ url_for('user.users', name=search_name, gender=search_gender, age=0) }}">전체</a>
  {% for i in range(10, 60, 10) %}
  <a class="filter {% if i == search_age %} selected {% endif %}"
    href="{{ url_for('user.users', name=search_name, gender=search_gender, age=i) }}">
    {{i}}대</a>
  {% endfor %}
</div>

<!-- 
==================
      table
==================
-->

{% if users %}
<table class="info-table">
  <thead>
    <tr class="info-row">
      {% for key in header %}
      <th class="info-type">
        {{ key }}
      </th>
      {% endfor %}
    </tr>
  </thead>
  <tbody>
    {% for user in users %}
    <tr class="info-row background">
      <td class="info-single-item">
        <a href="{{ url_for('user.user_detail', id=user.Id) }}">
          {{ user.Id }}
        </a>
      </td>
      <td class="info-single-item">
        {{ user.Name }}
      </td>
      <td class="info-single-item">
        {{ user.Gender }}
      </td>
      <td class="info-single-item">
        {{ user.Age }}
      </td>
      <td class="info-single-item">
        {{ user.Birthdate }}
      </td>
      <td class="info-single-item">
        {{ user.Address }}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %}

<!-- 
==================
    pagination
==================
-->

{% set keywords = "&name="+ search_name + "&gender=" + search_gender + "&age=" + search_age|string %}
{% include "common/pagination.html" %}
{% endblock %}